---

- name: Test
  hosts: ctns
  gather_facts: false
  tasks:
    - name: Print Hello World!
      ansible.builtin.debug:
        msg: "Hello World!"
    - name: Install apache
      ansible.builtin.yum:
        name: httpd
